"""PostgreSQL proof for derived Forecast Performance History and Learning Evidence."""
import hashlib, sys
from datetime import timedelta
from decimal import Decimal
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from uuid_extensions import uuid7
from app.application.actual_weekly_ledger import ActualWeeklyLedgerService
from app.application.effective_forecast_timeline import target_period_start
from app.application.forecast_evaluation_service import ForecastEvaluationService
from app.application.forecast_performance_history import ForecastPerformanceHistoryService
from app.database import SessionLocal
from app.models.actuals import ActualWeeklyObservation,ActualWeeklyRevision
from app.models.company import Company,User
from app.models.dataset import Dataset
from app.models.forecast_evaluation import ForecastEvaluation,ForecastEvaluationPoint
from app.models.forecast_vintage import ForecastVintage,ForecastVintagePoint
from app.models.learning import CompanyLearningMemory
from app.models.runtime import RuntimeExecution,RuntimeResultReference,RuntimeTask,RuntimeTaskAttempt
from app.models.security import CompanyEncryptionKey
from app.services.security import EncryptionService

def at(p): return target_period_start(p)
def row(code,p,q,level='finished_good',group='actual-group',klass='actual-class'): return {'material_code':code,'period':p,'quantity':q,'product_level':level,'product_group':group,'product_class':klass}
def add(s,cid,uid,did,label,available,cutoff,code,period,value,demand='sales',level='finished_good',group='group',klass='class',score=None):
 e=RuntimeExecution(execution_id=uuid7(),company_id=cid,user_id=uid,dataset_id=did,workflow_id='phase3aa6_'+label,analysis_type='forecast',state='completed');s.add(e);s.flush();r=RuntimeResultReference(company_id=cid,execution_id=e.execution_id,result_type='forecast',result_version='1.0.0',contract_version='1.0.0',storage_kind='inline_jsonb',inline_result={'fixture':label},validation_status='validated',created_at=available);s.add(r);s.flush();v=ForecastVintage(company_id=cid,execution_id=e.execution_id,runtime_result_reference_id=r.id,dataset_id=did,forecast_available_at=available,forecast_origin_period=cutoff,input_cutoff_period=cutoff,demand_type=demand,learning_score_at_run=score,result_version='1.0.0',contract_version='1.0.0');s.add(v);s.flush();s.add(ForecastVintagePoint(forecast_vintage_id=v.id,material_code=code,target_period=period,forecast_value=Decimal(str(value)),product_level=level,product_group=group,product_class=klass,horizon_index=1));s.flush()
def clean(s,cid,uid):
 ids=[x for x, in s.query(RuntimeExecution.execution_id).filter_by(company_id=cid)];vs=[x for x, in s.query(ForecastVintage.id).filter_by(company_id=cid)];es=[x for x, in s.query(ForecastEvaluation.id).filter_by(company_id=cid)];s.query(ForecastEvaluationPoint).filter(ForecastEvaluationPoint.evaluation_id.in_(es)).delete(synchronize_session=False);s.query(ForecastEvaluation).filter_by(company_id=cid).delete(synchronize_session=False);s.query(ForecastVintagePoint).filter(ForecastVintagePoint.forecast_vintage_id.in_(vs)).delete(synchronize_session=False);s.query(ForecastVintage).filter_by(company_id=cid).delete(synchronize_session=False);s.query(RuntimeResultReference).filter(RuntimeResultReference.execution_id.in_(ids)).delete(synchronize_session=False);s.query(RuntimeTaskAttempt).filter(RuntimeTaskAttempt.execution_id.in_(ids)).delete(synchronize_session=False);s.query(RuntimeTask).filter(RuntimeTask.execution_id.in_(ids)).delete(synchronize_session=False);s.query(RuntimeExecution).filter(RuntimeExecution.execution_id.in_(ids)).delete(synchronize_session=False);s.query(ActualWeeklyRevision).filter_by(company_id=cid).delete(synchronize_session=False);s.query(ActualWeeklyObservation).filter_by(company_id=cid).delete(synchronize_session=False);s.query(Dataset).filter_by(company_id=cid).delete(synchronize_session=False);s.query(CompanyEncryptionKey).filter_by(user_id=uid).delete(synchronize_session=False);s.query(User).filter_by(id=uid).delete(synchronize_session=False);s.query(Company).filter_by(id=cid).delete(synchronize_session=False);s.commit()
def sig(rows): return [(x.period,x.dimension_scope,x.dimension_value,x.sample_count,str(x.wape),tuple(str(y) for y in x.learning_scores_at_run),tuple(str(y) for y in x.source_evaluation_ids)) for x in rows]
def main():
 s=SessionLocal();cid=uid=None
 try:
  tag='phase3aa6_'+str(uuid7()).replace('-','');c=Company(id=uuid7(),name=tag,tax_id=tag);u=User(id=uuid7(),company_id=c.id,email=tag+'@x.invalid',hashed_password='x');s.add_all((c,u));s.flush();cid,uid=c.id,u.id;data={'items':[{'sku_code':'SKU-F','demand_history':[1]}]};d=Dataset(id=uuid7(),company_id=cid,user_id=uid,uploaded_by=uid,dataset_hash=hashlib.sha256(tag.encode()).hexdigest(),source_type=tag,encrypted_data=EncryptionService(s).encrypt_dataset(uid,data),is_active=True);s.add(d);s.commit();did=d.id
  ledger=ActualWeeklyLedgerService();ledger.ingest_dataset_actuals(cid,uid,did,[row('SKU-F','2026-W20',100),row('SKU-F','2026-W21',100),row('SKU-S','2026-W20',40,'semi_finished_good','semi-group','semi-class'),row('SKU-R','2026-W20',20,'raw_material','raw-group','raw-class')],'sales');ledger.ingest_dataset_actuals(cid,uid,did,[row('SKU-F','2026-W20',55)],'shipment');ledger.ingest_dataset_actuals(cid,uid,did,[row('SKU-Z','2026-W20',0)],'order')
  s.close();s=SessionLocal();add(s,cid,uid,did,'F20',at('2026-W19'),'2026-W19','SKU-F','2026-W20',90,group='fg-group',klass='fg-class',score=Decimal('30'));add(s,cid,uid,did,'F21',at('2026-W20'),'2026-W20','SKU-F','2026-W21',80,group='fg-group',klass='fg-class',score=Decimal('57'));add(s,cid,uid,did,'F22',at('2026-W21'),'2026-W21','SKU-F','2026-W22',90,group='fg-group',klass='fg-class',score=Decimal('87'));add(s,cid,uid,did,'S',at('2026-W19'),'2026-W19','SKU-S','2026-W20',30,level='semi_finished_good',group='semi-group',klass='semi-class',score=Decimal('30'));add(s,cid,uid,did,'R',at('2026-W19'),'2026-W19','SKU-R','2026-W20',25,level='raw_material',group='raw-group',klass='raw-class');add(s,cid,uid,did,'ship',at('2026-W19'),'2026-W19','SKU-F','2026-W20',50,demand='shipment');add(s,cid,uid,did,'zero',at('2026-W19'),'2026-W19','SKU-Z','2026-W20',0,demand='order');s.commit()
  evaluator=ForecastEvaluationService(s);initial=evaluator.evaluate(cid,'sales','2026-W20','2026-W22');evaluator.evaluate(cid,'shipment','2026-W20','2026-W20');evaluator.evaluate(cid,'order','2026-W20','2026-W20');s.commit();history=ForecastPerformanceHistoryService(s);company=history.weekly_history(cid,'sales','2026-W20','2026-W22');assert [x.period for x in company]==['2026-W20','2026-W21'] and company[0].sample_count==3 and company[0].evaluated_period_count==1 and company[0].first_evaluated_period=='2026-W20' and company[1].learning_score_at_run==Decimal('57') and company[1].learning_scores_at_run==(Decimal('57'),)
  assert history.weekly_history(cid,'sales','2026-W20','2026-W22','product_level','finished_good')[0].sample_count==1 and history.weekly_history(cid,'sales','2026-W20','2026-W22','product_level','semi_finished_good')[0].sample_count==1 and history.weekly_history(cid,'sales','2026-W20','2026-W22','product_level','raw_material')[0].sample_count==1 and history.weekly_history(cid,'sales','2026-W20','2026-W22','product_group','fg-group')[0].dimension_value=='fg-group' and history.weekly_history(cid,'sales','2026-W20','2026-W22','product_class','fg-class')[0].dimension_value=='fg-class' and history.weekly_history(cid,'sales','2026-W20','2026-W22','material_code','SKU-F')[0].dimension_value=='SKU-F'
  assert history.weekly_history(cid,'shipment','2026-W20','2026-W20')[0].sample_count==1 and history.weekly_history(cid,'order','2026-W20','2026-W20')[0].wape is None and history.weekly_history(cid,'order','2026-W20','2026-W20')[0].wape_unavailable_reason=='zero_actual_denominator'
  before=(s.query(ForecastEvaluation).filter_by(company_id=cid).count(),s.query(ForecastEvaluationPoint).join(ForecastEvaluation).filter(ForecastEvaluation.company_id==cid).count(),s.query(CompanyLearningMemory).filter_by(company_id=cid).count());assert sig(history.weekly_history(cid,'sales','2026-W20','2026-W22'))==sig(company) and (s.query(ForecastEvaluation).filter_by(company_id=cid).count(),s.query(ForecastEvaluationPoint).join(ForecastEvaluation).filter(ForecastEvaluation.company_id==cid).count(),s.query(CompanyLearningMemory).filter_by(company_id=cid).count())==before
  ledger.ingest_dataset_actuals(cid,uid,did,[row('SKU-F','2026-W22',100)],'sales');evaluator.evaluate(cid,'sales','2026-W20','2026-W22');s.commit();arrival=history.weekly_history(cid,'sales','2026-W20','2026-W22');assert [x.period for x in arrival]==['2026-W20','2026-W21','2026-W22'] and arrival[-1].learning_score_at_run==Decimal('87')
  proposal=ledger.ingest_dataset_actuals(cid,uid,did,[row('SKU-F','2026-W21',120)],'sales');ledger.approve_revision(cid,proposal['revision_ids'][0],uid);evaluator.evaluate(cid,'sales','2026-W20','2026-W22');s.commit();corrected=history.weekly_history(cid,'sales','2026-W20','2026-W22');assert corrected[1].wape==Decimal('40')/Decimal('120')
  proposal=ledger.ingest_dataset_actuals(cid,uid,did,[row('SKU-F','2026-W20',150)],'sales');ledger.reject_revision(cid,proposal['revision_ids'][0],uid);evaluator.evaluate(cid,'sales','2026-W20','2026-W22');s.commit();assert sig(history.weekly_history(cid,'sales','2026-W20','2026-W22'))==sig(corrected)
  expected=sig(corrected);s.close();s=SessionLocal();fresh=ForecastPerformanceHistoryService(s).weekly_history(cid,'sales','2026-W20','2026-W22');assert sig(fresh)==expected and s.query(CompanyLearningMemory).filter_by(company_id=cid).count()==0
  print('PHASE3AA6 PASS',{'weekly_rows':len(fresh),'sample_strength':company[0].sample_count,'new_actual':'W22','correction':'W21 100->120','learning_side_effects':0},flush=True)
 finally:
  if s and cid: clean(s,cid,uid)
  elif s:s.close()
if __name__=='__main__':main()
