import asyncio,hashlib,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from uuid_extensions import uuid7
from app.application.actual_weekly_ledger import ActualWeeklyLedgerService
from app.application.champion_rollback import ChampionRollbackService
from app.application.business_workflow_acceptance import BusinessWorkflowAcceptanceService
from app.application.xgboost_champion_inference import XGBoostChampionInferenceService
from app.application.workflow_dispatcher import WorkflowDispatcher
from app.database import SessionLocal
from app.engine.local_forecast_runner import LocalForecastRunner
from app.engine.business_workflow_scheduler import BusinessWorkflowScheduler
from app.models.actuals import ActualWeeklyObservation,ActualWeeklyRevision
from app.models.company import User
from app.models.dataset import Dataset
from app.models.forecast_vintage import ForecastVintage,ForecastVintagePoint
from app.models.runtime import RuntimeExecution,RuntimeResultReference,RuntimeTask,RuntimeTaskAttempt
from app.models.security import CompanyEncryptionKey
from app.services.security import EncryptionService
from app.services.model_artifact_storage import LocalModelArtifactStorage
from scripts.support.rollback_xgboost_fixture import create,cleanup
def main():
 ids=refs=fallback_ids=fallback_refs=None;s=None;uid=did=fallback_uid=fallback_did=None
 try:
  ids,refs=create();fallback_ids,fallback_refs=create(material_code='FALLBACK',demand_type='sales',product_level='finished_good');s=SessionLocal();u=User(id=uuid7(),company_id=ids.company_id,email='r3_'+str(uuid7())+'@x.invalid',hashed_password='x');s.add(u);s.flush();uid=u.id;payload={'items':[{'sku_code':ids.material_code,'demand_history':[100+w for w in range(32)],'lead_time_days':7,'initial_stock':500,'eoq':100}]};d=Dataset(id=uuid7(),company_id=ids.company_id,user_id=uid,uploaded_by=uid,dataset_hash=hashlib.sha256(str(ids.company_id).encode()).hexdigest(),source_type='r3_fixture',encrypted_data=EncryptionService(s).encrypt_dataset(uid,payload),is_active=True);s.add(d);s.commit();did=d.id
  ActualWeeklyLedgerService().ingest_dataset_actuals(ids.company_id,uid,did,[{'material_code':ids.material_code,'period':f'2026-W{w:02d}','quantity':100+w,'product_level':'finished_good'} for w in range(1,33)],ids.demand_type)
  s=SessionLocal();fu=User(id=uuid7(),company_id=fallback_ids.company_id,email='fallback_'+str(uuid7())+'@x.invalid',hashed_password='x');s.add(fu);s.flush();fallback_uid=fu.id;fpayload={'items':[{'sku_code':'FALLBACK','demand_history':[100+w for w in range(32)],'lead_time_days':7,'initial_stock':500,'eoq':100}]};fd=Dataset(id=uuid7(),company_id=fallback_ids.company_id,user_id=fallback_uid,uploaded_by=fallback_uid,dataset_hash=hashlib.sha256(str(fallback_ids.company_id).encode()).hexdigest(),source_type='r3_fallback_fixture',encrypted_data=EncryptionService(s).encrypt_dataset(fallback_uid,fpayload),is_active=True);s.add(fd);s.commit();fallback_did=fd.id;ActualWeeklyLedgerService().ingest_dataset_actuals(fallback_ids.company_id,fallback_uid,fallback_did,[{'material_code':'FALLBACK','period':f'2026-W{w:02d}','quantity':100+w,'product_level':'finished_good'} for w in range(1,33)],'sales');s.close();s=None
  async def run_fallback():
   p={'horizon':2,'forecast_vintage':{'demand_type':'sales','product_metadata':{'FALLBACK':{'product_level':'finished_good'}}}};e=await WorkflowDispatcher().dispatch_single_analysis(fallback_ids.company_id,fallback_uid,fallback_did,'forecast',['FALLBACK'],p);r=await LocalForecastRunner().run(e['execution_id']);return e['execution_id'],r.id
  fallback_execution_id,fallback_reference_id=asyncio.run(run_fallback());s=SessionLocal();fallback_execution=s.query(RuntimeExecution).filter_by(execution_id=fallback_execution_id).one();fallback_item=s.query(RuntimeResultReference).filter_by(id=fallback_reference_id).one().inline_result['items'][0];assert fallback_execution.metadata_['params']['scope_mode']=='current_canonical' and fallback_execution.metadata_['params']['forecast_cutoff_period']=='2026-W32' and fallback_item['selection_info']['champion_registry_entry_id']==str(fallback_ids.entry_c_id);s.close();s=None
  params={'horizon':2,'forecast_vintage':{'demand_type':ids.demand_type,'product_metadata':{ids.material_code:{'product_level':'finished_good'}}}}
  async def run():
   e=await WorkflowDispatcher().dispatch_single_analysis(ids.company_id,uid,did,'forecast',[ids.material_code],params);r=await LocalForecastRunner().run(e['execution_id']);return e['execution_id'],r.id
  pre_e,pre_r=asyncio.run(run());s=SessionLocal();pre_ref=s.query(RuntimeResultReference).filter_by(id=pre_r).one();pre_item=pre_ref.inline_result['items'][0];pre_v=s.query(ForecastVintage).filter_by(runtime_result_reference_id=pre_r).one();pre_points=tuple((x.target_period,float(x.forecast_value)) for x in s.query(ForecastVintagePoint).filter_by(forecast_vintage_id=pre_v.id).order_by(ForecastVintagePoint.horizon_index));assert pre_item['selection_info']['champion_registry_entry_id']==str(ids.entry_c_id);snapshot=(pre_r,pre_v.id,pre_item['selection_info']['model_artifact_id'],pre_item['selection_info']['artifact_checksum'],tuple(pre_item['forecast']),pre_points,pre_v.input_cutoff_period,pre_v.demand_type);s.close();s=None
  rollback=ChampionRollbackService().rollback(ids.company_id,ids.material_code,ids.demand_type,ids.entry_c_id,ids.entry_b_id,'R3 fixture rollback');assert rollback.status=='ROLLED_BACK';post_e,post_r=asyncio.run(run());s=SessionLocal();post=s.query(RuntimeResultReference).filter_by(id=post_r).one().inline_result['items'][0];post_v=s.query(ForecastVintage).filter_by(runtime_result_reference_id=post_r).one();assert post['selection_info']['champion_registry_entry_id']==str(ids.entry_b_id) and post['selection_info']['model_artifact_id']==str(ids.artifact_b_id)
  business=BusinessWorkflowAcceptanceService().accept_or_resolve(ids.company_id,uid,did,request_metadata={'params':params});assert business.status=='CREATED';completed=[]
  while True:
   q=SessionLocal();ready=[x for x in BusinessWorkflowScheduler(q).readiness(business.execution_id,ids.company_id) if x['ready']];q.close()
   if not ready:break
   completed.append(ready[0]['task_id']);assert asyncio.run(LocalForecastRunner().run_business_task(business.execution_id,ids.company_id,ready[0]['task_id']))
  execution=s.query(RuntimeExecution).filter_by(execution_id=business.execution_id).one();brefs={x.result_type:x for x in s.query(RuntimeResultReference).filter_by(execution_id=business.execution_id).all()};bitem=brefs['forecast'].inline_result['items'][0];assert completed==['forecast','safety_stock','simulation','backtest'] and execution.state=='completed' and float(execution.progress)==100 and bitem['selection_info']['model_artifact_id']==str(ids.artifact_b_id)
  fcur=s.query(__import__('app.models.champion_registry',fromlist=['ChampionRegistryCurrent']).ChampionRegistryCurrent).filter_by(company_id=fallback_ids.company_id,material_code='FALLBACK',demand_type='sales').one();fstate=(fcur.active_entry_id,fcur.row_version,s.query(__import__('app.models.champion_registry',fromlist=['ChampionRegistryTransition']).ChampionRegistryTransition).filter_by(company_id=fallback_ids.company_id,transition_type='ROLLBACK').count());fc=s.query(__import__('app.models.model_artifact',fromlist=['ModelArtifact']).ModelArtifact).filter_by(id=fallback_ids.artifact_c_id).one();LocalModelArtifactStorage().base_directory.joinpath(fc.artifact_storage_reference).write_bytes(b'corrupt');s.close();s=None;fallback_execution_id,fallback_bad_ref=asyncio.run(run_fallback());s=SessionLocal();fallback_item=s.query(RuntimeResultReference).filter_by(id=fallback_bad_ref).one().inline_result['items'][0];fcur=s.query(__import__('app.models.champion_registry',fromlist=['ChampionRegistryCurrent']).ChampionRegistryCurrent).filter_by(company_id=fallback_ids.company_id,material_code='FALLBACK',demand_type='sales').one();assert fallback_item['selection_info']['champion_resolution']=='fallback_classical' and (fcur.active_entry_id,fcur.row_version,s.query(__import__('app.models.champion_registry',fromlist=['ChampionRegistryTransition']).ChampionRegistryTransition).filter_by(company_id=fallback_ids.company_id,transition_type='ROLLBACK').count())==fstate;s.close();s=None;fallback_rollback=ChampionRollbackService().rollback(fallback_ids.company_id,'FALLBACK','sales',fallback_ids.entry_c_id,fallback_ids.entry_a_id,'explicit after fallback');assert fallback_rollback.status=='ROLLED_BACK'
  s=SessionLocal();old=s.query(RuntimeResultReference).filter_by(id=pre_r).one().inline_result['items'][0];old_v=s.query(ForecastVintage).filter_by(id=pre_v.id).one();old_points=tuple((x.target_period,float(x.forecast_value)) for x in s.query(ForecastVintagePoint).filter_by(forecast_vintage_id=old_v.id).order_by(ForecastVintagePoint.horizon_index));assert (pre_r,old_v.id,old['selection_info']['model_artifact_id'],old['selection_info']['artifact_checksum'],tuple(old['forecast']),old_points,old_v.input_cutoff_period,old_v.demand_type)==snapshot;print('PHASE3C3B3B2 R3 FIXTURE PASS',{'pre_execution_id':str(pre_e),'post_execution_id':str(post_e),'business_execution_id':str(business.execution_id),'fallback_rollback_transition_id':str(fallback_rollback.transition_id),'rollback_transition_id':str(rollback.transition_id)})
 finally:
  if s:s.close()
  if ids:
   s=SessionLocal();eids=[x[0] for x in s.query(RuntimeExecution.execution_id).filter_by(company_id=ids.company_id)];vids=[x[0] for x in s.query(ForecastVintage.id).filter_by(company_id=ids.company_id)];s.query(ForecastVintagePoint).filter(ForecastVintagePoint.forecast_vintage_id.in_(vids)).delete(synchronize_session=False);s.query(ForecastVintage).filter(ForecastVintage.id.in_(vids)).delete(synchronize_session=False);s.query(RuntimeResultReference).filter(RuntimeResultReference.execution_id.in_(eids)).delete(synchronize_session=False);s.query(RuntimeTaskAttempt).filter(RuntimeTaskAttempt.execution_id.in_(eids)).delete(synchronize_session=False);s.query(RuntimeTask).filter(RuntimeTask.execution_id.in_(eids)).delete(synchronize_session=False);s.query(RuntimeExecution).filter(RuntimeExecution.execution_id.in_(eids)).delete(synchronize_session=False);s.query(ActualWeeklyRevision).filter_by(company_id=ids.company_id).delete(synchronize_session=False);s.query(ActualWeeklyObservation).filter_by(company_id=ids.company_id).delete(synchronize_session=False);s.query(Dataset).filter_by(company_id=ids.company_id).delete(synchronize_session=False);s.query(CompanyEncryptionKey).filter_by(user_id=uid).delete(synchronize_session=False);s.query(User).filter_by(id=uid).delete(synchronize_session=False);s.commit();s.close();cleanup(ids,refs)
  if fallback_ids:
   s=SessionLocal();feids=[x[0] for x in s.query(RuntimeExecution.execution_id).filter_by(company_id=fallback_ids.company_id)];fvids=[x[0] for x in s.query(ForecastVintage.id).filter_by(company_id=fallback_ids.company_id)];s.query(ForecastVintagePoint).filter(ForecastVintagePoint.forecast_vintage_id.in_(fvids)).delete(synchronize_session=False);s.query(ForecastVintage).filter(ForecastVintage.id.in_(fvids)).delete(synchronize_session=False);s.query(RuntimeResultReference).filter(RuntimeResultReference.execution_id.in_(feids)).delete(synchronize_session=False);s.query(RuntimeTaskAttempt).filter(RuntimeTaskAttempt.execution_id.in_(feids)).delete(synchronize_session=False);s.query(RuntimeTask).filter(RuntimeTask.execution_id.in_(feids)).delete(synchronize_session=False);s.query(RuntimeExecution).filter(RuntimeExecution.execution_id.in_(feids)).delete(synchronize_session=False);s.query(ActualWeeklyRevision).filter_by(company_id=fallback_ids.company_id).delete(synchronize_session=False);s.query(ActualWeeklyObservation).filter_by(company_id=fallback_ids.company_id).delete(synchronize_session=False);s.query(Dataset).filter_by(company_id=fallback_ids.company_id).delete(synchronize_session=False);s.query(CompanyEncryptionKey).filter_by(user_id=fallback_uid).delete(synchronize_session=False);s.query(User).filter_by(id=fallback_uid).delete(synchronize_session=False);s.commit();s.close();cleanup(fallback_ids,fallback_refs)
if __name__=='__main__':main()
