"""
AI Artifact Model - DOCUMENT 06A AI Artifact Standard
Implementation of AA-001 AI Artifact Model
"""

from sqlalchemy import Column, String, Integer, Boolean, DateTime, ForeignKey, JSON, Index
from sqlalchemy.dialects.postgresql import UUID as PG_UUID, JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.models.base import BaseModel


class AIArtifact(BaseModel):
    """
    AI Artifact Standard - Document 06A
    
    Every communication output generated by Decision Intelligence
    SHALL become an AI Artifact.
    
    AI Artifacts SHALL represent the only official communication objects
    exposed to users, dashboards, reports and external APIs.
    """
    __tablename__ = "ai_artifacts"

    # ====================================================================
    # COMMON METADATA
    # ====================================================================
    artifact_type = Column(String, nullable=False, index=True)  # analysis_narrative, executive_timeline, executive_advisor
    artifact_subtype = Column(String, nullable=True, index=True)  # REVISION 04 - Future types
    
    company_id = Column(PG_UUID(as_uuid=True), ForeignKey("companies.id"), nullable=False, index=True)
    dataset_id = Column(PG_UUID(as_uuid=True), ForeignKey("datasets.id"), nullable=True, index=True)
    execution_id = Column(PG_UUID(as_uuid=True), ForeignKey("execution_results.id"), nullable=True, index=True)  # REVISION 05 - UUID only
    
    language = Column(String, default="tr")
    
    # ====================================================================
    # VERSIONING (AA-005)
    # ====================================================================
    prompt_version = Column(String, nullable=True)
    schema_version = Column(String, default="1.0")
    communication_contract_version = Column(String, default="1.0")
    artifact_version = Column(Integer, default=1)
    
    # ====================================================================
    # LLM PROVIDER (AA-006)
    # ====================================================================
    llm_provider = Column(String, nullable=True)
    llm_model = Column(String, nullable=True)
    model_version = Column(String, nullable=True)
    
    # ====================================================================
    # CONTENT (AA-003)
    # ====================================================================
    content = Column(JSONB, nullable=False)  # Structured JSON with Header, Business Content, Explainability, Supporting Evidence, Metadata
    
    # ====================================================================
    # STATUS & VALIDATION (AA-004)
    # ====================================================================
    status = Column(String, default="draft")  # draft, validated, published, archived
    validation_status = Column(String, nullable=True)
    validation_errors = Column(JSONB, nullable=True)
    validated_at = Column(DateTime, nullable=True)
    validated_by = Column(PG_UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    
    # ====================================================================
    # REUSE (AA-009)
    # ====================================================================
    is_reused = Column(Boolean, default=False)
    reused_from_artifact_id = Column(PG_UUID(as_uuid=True), ForeignKey("ai_artifacts.id"), nullable=True)
    reuse_count = Column(Integer, default=0)
    
    # ====================================================================
    # AUDIT
    # ====================================================================
    generated_by = Column(PG_UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    generated_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # ====================================================================
    # RELATIONSHIPS
    # ====================================================================
    company = relationship("Company", back_populates="ai_artifacts")
    dataset = relationship("Dataset", back_populates="ai_artifacts")
    execution = relationship("ExecutionResult", back_populates="ai_artifacts")
    user = relationship("User", foreign_keys=[generated_by])
    validator = relationship("User", foreign_keys=[validated_by])
    reused_from = relationship("AIArtifact", remote_side=[id])
    
    # ====================================================================
    # INDEXES
    # ====================================================================
    __table_args__ = (
        Index("ix_ai_artifacts_company_type_status", "company_id", "artifact_type", "status"),
        Index("ix_ai_artifacts_company_execution", "company_id", "execution_id"),
        Index("ix_ai_artifacts_company_dataset", "company_id", "dataset_id"),
        Index("ix_ai_artifacts_created_at", "created_at"),
    )